server:
  port : 9191 


spring:
 cloud:
   gateway:
     routes:
     - id: USER_MICROSERVICE
       uri: http://localhost:9002/
       predicates:
       - Path=/api/user/**
#       filters:
#        - name: CircuitBreaker
#          args:
#            name: myCircuitBreaker
#            fallbackUri: forward:/fallback/userCallBackMethod
     - id: DEPARTMENT_MICROSERVICE
       uri: http://localhost:9001/
       predicates:
       - Path=/api/department/**
 
 application:
   name: API-GATEWAY


eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      registerWithEureka: true
      fetchRegistry: true