server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include:
        - health
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
        
resilience4j:
  circuitbreaker:
    instances:
        ServiceA:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 20
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            automatic-transition-from-open-to-half-open-enabled: true
resilience4j.retry:
    instances:
        backendA:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2  